### ISSUE TITLE
无法下载第二页的内容

### ISSUE THREAD

**Issue by tonylu00** [0NG/sslibrary-pdf-downloader#1]
只有第一页的搜索结果可以下载，从第二页开始报错
Traceback (most recent call last):
  File "download.py", line 121, in <module>
    url = getDownloadLink(result[choice]['buttonurl'])
  File "download.py", line 60, in getDownloadLink
    fileMark = reg_fileMark.search(page).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

接口返回的数据是“本书已下架”
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">    <title>错误页面</title></head><body><div>    <p><em>本书已经下架</em></p></div><div style="display: none;">    status:     path:     parameters:    fileMark: 12950853    fileName: ARM CORTEX-A8处理器原理与应用  基于TI AM367X/DM37X处理器    pages: -1    readerType: 1    enc: 46f5d8ce235ee0ab310efcf7557c3dba    time: 1530929241465    classifyId: 1817040502    errorMsg:     exception: </div></body></html>

**Comment by 0NG** [comment]
谢谢！之前是临时用，没考虑太多。刚考完期末，我来修补一些问题吧~
另外，你搜索的关键词是什么呢？我没搜到这本书诶。

**Comment by tonylu00** [comment]
关键词"ARM"，这本书在第二页

**Comment by 0NG** [comment]
emmm我还是没有搜索到《CORTEX-A8处理器原理与应用》这本书，Cortex-A8相关的只有一本《ARM Cortex-A8嵌入式系统开发与实践 WinCE与Android平台》，暂时无法复现这个问题。这个脚本的搜索结果和我浏览器看到的搜索结果是一样的。
![image](https://user-images.githubusercontent.com/15275387/42418672-c4774a4e-82d7-11e8-8152-67f6ae2ab081.png)

可能真的已经下架？或许也可能是因为那本书只有扫描版？我更新了脚本了，现在可以下载pdf版和图片版了，你再试试看行不行。
可以的话，麻烦把[代码里的readerUrl](https://github.com/0NG/sslibrary-pdf-downloader/blob/master/download.py#L59)和[下面的downloadInfo](https://github.com/0NG/sslibrary-pdf-downloader/blob/master/download.py#L152)输出出来给我，我好看看是怎么回事。

**Comment by tonylu00** [comment]
感谢回复，支持扫描版书籍之后问题解决了。
一些关键词只有第一页才有PDF版的书籍(PDF版优先排序?)，从第二页开始绝大多数是扫描的，所以会让我产生这种错觉
