### ISSUE TITLE
书会混乱

### ISSUE THREAD

**Issue by 869909419** [0NG/sslibrary-pdf-downloader#15]
就下载的书会出现其他的书作者能看看吗

**Comment by 0NG** [comment]
啥意思？？？没看懂。而且在我这里测试，发现sslibrary的api已经改变，目前这个代码是搜索不到书籍的（逃

**Comment by 869909419** [comment]
就是依然可以用这个代码下载，但是下载出的书的内容 出现其他书里面的内容

**Comment by 0NG** [comment]
那可能和我目前发现的问题有关吧。但是已弃坑了，有需要请查看代码修正bug即可。
