### ISSUE TITLE
无法找到PIL

### ISSUE THREAD

**Issue by PumpkinSin** [0NG/sslibrary-pdf-downloader#4]
=提示```
Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

**Comment by 0NG** [comment]
是Pillow，已改，谢谢

**Comment by zhaoworking** [comment]
I also met this issue just now. Turn to your envs,and pip install Pillow.And If the downloading speed is slow,you can try to install again.
