### ISSUE TITLE
请问为什么每次下载图片时获取cookie？

### ISSUE THREAD

**Issue by Azureki** [0NG/sslibrary-pdf-downloader#8]
cookie获取一次就可以了吧？每次调用`threadDownloadImg`时都调用了一次`_getCookie`，在里面调用了两次`requests.get()`，但下载这些图片时用的cookie不是相同的吗？还是说下载每张图片用的cookie都不一样？

**Comment by 0NG** [comment]
记不太清了，看了下代码，貌似是当时发现response会要求更新cookie，忘了跟什么有关了，之前代码里传的是ua，那可能是ua变就会导致cookie变。两次get应该是，第一次会要求重定向，然后再获取一次cookie，当时这块确实很麻烦，也没时间去弄懂怎么回事，就这么照着浏览器上的请求顺序，模拟着来。

**Comment by Azureki** [comment]
@0NG 

感谢回复。
确实是这样的。如果连续下载图片就会要求输入验证码，并且不使用`ThreadPool`，每次sleep一秒，也还是如此。

因为我现在没有校园网，在浏览器登录图书馆才可以使用学校VPN访问sslibrary。所以我直接把浏览器cookies复制到本地然后抓取，但果然不行，只能下20多页。

所以重复获取cookie还是必要的。
